name: CI

on:
  push:
    branches: [main, master, develop]
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v1.2.3, etc.)
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Build package (includes type checking)
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Build docs
        run: yarn docs:build

      - name: Upload coverage to Codecov
        if: matrix.node-version == '22.x'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  publish:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      startsWith(github.ref, 'refs/tags/v') &&
      github.repository == 'ooguzyuksel/react-timedown'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

