name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == 'ooguzyuksel/react-timedown'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Build package
        run: yarn build

      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          yarn version --${{ github.event.inputs.version_type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git add package.json
          git commit -m "chore: release v${{ steps.bump_version.outputs.new_version }}"

      - name: Create tag
        run: git tag v${{ steps.bump_version.outputs.new_version }}

      - name: Push changes
        run: |
          git push origin master
          git push origin v${{ steps.bump_version.outputs.new_version }}

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate changelog
        id: changelog
        run: |
          if [ "${{ steps.current_version.outputs.version }}" = "1.0.4" ]; then
            echo "## 🎉 Fully Automated Release System" > CHANGELOG_RELEASE.md
            echo "" >> CHANGELOG_RELEASE.md
            echo "This release includes the complete automation of the release process:" >> CHANGELOG_RELEASE.md
            echo "" >> CHANGELOG_RELEASE.md
          fi
          git log v${{ steps.current_version.outputs.version }}..v${{ steps.bump_version.outputs.new_version }} --pretty=format:"- %s (%h)" >> CHANGELOG_RELEASE.md || echo "- Release v${{ steps.bump_version.outputs.new_version }}" > CHANGELOG_RELEASE.md
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG_RELEASE.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: Release v${{ steps.bump_version.outputs.new_version }}
          body: |
            ## Changes in this release
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            ```bash
            npm install @ooguzyuksel/react-timedown@${{ steps.bump_version.outputs.new_version }}
            ```
            
            or
            
            ```bash
            yarn add @ooguzyuksel/react-timedown@${{ steps.bump_version.outputs.new_version }}
            ```
            
            ## Links
            
            - 📦 [NPM Package](https://www.npmjs.com/package/@ooguzyuksel/react-timedown/v/${{ steps.bump_version.outputs.new_version }})
            - 📚 [Documentation](https://react-timedown.netlify.app/)
            - 🎨 [Storybook Examples](https://ooguzyuksel.github.io/react-timedown/)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Summary
        run: |
          echo "## 🎉 Release Created Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Version Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Previous Version:** ${{ steps.current_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **New Version:** ${{ steps.bump_version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version Type:** ${{ github.event.inputs.version_type }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Completed Actions" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Tests**: All tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Build**: Package built successfully" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Version**: Updated to v${{ steps.bump_version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Git**: Committed and tagged" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **NPM**: Published to NPM registry" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **GitHub Release**: Created release v${{ steps.bump_version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "The following workflows will run automatically:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Deploy Storybook**: Update Storybook" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Links" >> $GITHUB_STEP_SUMMARY
          echo "- [NPM Package](https://www.npmjs.com/package/@ooguzyuksel/react-timedown)" >> $GITHUB_STEP_SUMMARY
          echo "- [Releases](https://github.com/${{ github.repository }}/releases)" >> $GITHUB_STEP_SUMMARY
          echo "- [Storybook](https://ooguzyuksel.github.io/react-timedown/)" >> $GITHUB_STEP_SUMMARY

