name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Build package
        run: yarn build

      - name: Generate changelog
        id: changelog
        run: |
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" > CHANGELOG_RELEASE.md
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG_RELEASE.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            ```bash
            npm install @ooguzyuksel/react-timedown@${{ github.ref_name }}
            ```
            
            or
            
            ```bash
            yarn add @ooguzyuksel/react-timedown@${{ github.ref_name }}
            ```
            
            ## Links
            
            - 📦 [NPM Package](https://www.npmjs.com/package/@ooguzyuksel/react-timedown)
            - 📚 [Documentation](https://ooguzyuksel.github.io/react-timedown/)
            - 🎨 [Storybook Examples](https://ooguzyuksel.github.io/react-timedown/)
          draft: false
          prerelease: false

